### ISSUE TITLE
Vim-css-color doesnt work.

### ISSUE THREAD

**Issue by Figuera** [skammer/vim-css-color#10]
First sorry for the other topic, just stupid mistake.

Ok vim css color is not working for me, I run :scriptnames as suggested and the plugin IS being loaded, as we can see:

 39: /home/caio/.vim/after/syntax/css.vim

**Comment by ap** [comment]
What does `:echo 'gui:' has("gui_running") 'term:' &t_Co+0` say?

**Comment by Figuera** [comment]
0 0

This is bad isnt it?

**Comment by ap** [comment]
That means you are either running vim in a 16-colour terminal&#x2009;—&#x2009;in which case the script simply _cannot_ work&#x2009;—, or that vim _thinks_ you are running it in such&#x2009;—&#x2009;in which case you’re in luck if overriding it with `:set t_Co=256` before loading a CSS file works, or else I can’t help you&#x200a;—&#x200a;sorry&#x200a;—&#x200a;if it doesn’t.

**Comment by Figuera** [comment]
It's doesn't but thanks for your effort.

A fun fact is that i just type #FFFF00 and then there it is, and I was all =DDDDD, but than i change the code to some other color and nothings happen again, it must be something with my terminal right? I am running a regular Gnome terminal 2.3

Oh wait its working!! its just VERY slow, and some awkward colors just take forever to show up.

**Comment by ap** [comment]
Yes, the script will pick one of the 16 regular console colours when that is possible so if you force it to work, it will accidentally work for a small handful of CSS colour values. It could even be changed to highlight them all. But that would be useless because with only 16 colours, the highlights would be nothing like what the colour values say.

I don’t know how to configure Gnome Terminal for 256 colour support, but if you look around you’ll probably find something.

**Comment by millermedeiros** [comment]
I was having issues with the plugin as well and just realized that the [CSS syntax file](https://github.com/ChrisYip/Better-CSS-Syntax-for-Vim/issues/4) was causing the conflict.

**Comment by ap** [comment]
That has nothing to do with the problem that was under discussion here.

**Comment by fiskus** [comment]
Does this plugin work in gVim only, not in Vim?

**Comment by ap** [comment]
If you have a 256 colour terminal it will work in console vim, but with limited fidelity – naturally, since the terminal only supports 256 colours (whereas 24 bit = 16 million colours). But it’s good enough for a rough idea at a glance.

**Comment by fiskus** [comment]
I just changed "Report Terminal Type" from `xterm-new` to `xterm-256color`, in iTerm -> Preferences -> Profiles -> Terminal, and it works now. Thanks.

**Comment by wenLiangcan** [comment]
Same here, the script does not work for both vim and gvim. I'm using terminator and has the setting `set t_Co=256` in .vimrc.

**Comment by pandagxnu** [comment]
It's works on Mac OS X 10.9.3 . But it does't work on Debian GNU/Linux Jessie with GNOME-Terminal 3.12 or Terminator . The .vimrc on OS X is copied from GNU/Linux, of course has the setting 
"set t_Co=256" in .vimrc.
Same here
I run :script names and see ~/.vim/after/syntax/css.vim ,
when run  :echo 'gui:'  get gui:

**Comment by ap** [comment]
Does [my fork](/ap/vim-css-color) work for you?

**Comment by paquai13** [comment]
@ap your fork works for me with MacVim 7.4

Maybe you could fill in a pull request ?

**Comment by ap** [comment]
I have no plans to do that. I have completely rewritten the code (several times over by now), it has a very different plugin structure, etc. I am also still actively maintaining my version. (C.f. [GitHub forking has one big flaw](http://zbowling.github.io/blog/2011/11/25/github/).)

**Comment by paquai13** [comment]
@ap good to know. Your fork seems to be more maintained indeed. I think I'll stick to it ;) Thank you.

**Comment by tremby** [comment]
For me, this repository highlights as long as the colour string doesn't come after a colon. For CSS files that makes it rather useless. @ap's fork works for me.

**Comment by tellok** [comment]
@ap  yeah, your folk works awesome for me.

**Comment by imkeke** [comment]
@ap Your fork is great.

**Comment by tetreault** [comment]
Hello, 

I'm using Vim version 8.0.134 on MacOS Sierra v10.12.2 and on my AWS EC2 Amazon Linux instances. I've installed the plugin using Vundle but it doesn't highlight any colors in the css file, for example: `background-color: red;`. How should I go about trouble shooting this? 

I've also tried adding set t_Co=256 in my vimrc with no luck.

**Comment by ap** [comment]
> How should I go about trouble shooting this?

What does `:set ft?` say when you’re in that buffer? Does `:scriptnames` say that the plugin ran?

**Comment by tetreault** [comment]
Thanks for the quick response @ap. `:set ft` returns just `  filetype=   `. Interestingly enough,  `:scriptnames`doesn't show vim-css-color in it so i guess that explains it. I'm still not sure what the issue is though in regards to why it didn't install through Vundle. I included it just like like i do any other plugin in my .vimrc file like so `Plugin 'tetreault/vim-css-color'` (I forked it) and then run `:PluginInstall`.

**Comment by ap** [comment]
It may well have installed just fine. Your problem is almost certainly that `filetype` is not getting set.

Does any `syntax/css.vim` file at all get loaded? If not, then it’s entirely expectable that this plugin didn’t either – because it uses Vim’s `after` mechanism to extend your existing `css` filetype syntax. So if no base `css` syntax is loaded, the plugin won’t be either.

Now Vim ships with a default `css` syntax and loads it by default in a stock install, so the thing you need to figure out is why your configuration causes that to not happen. If you get to the point where `:set ft?` says `filetype=css`, my bet is that vim-css-color will then also start working, all by itself.

If you say `:set ft=css` manually, what happens? Does vim-css-color get loaded?

**Comment by tetreault** [comment]
Thanks for the response @ap , much appreciated since I've only been using Vim seriously for like a month and a half now. 

Yeah, I didn't see any `syntax/vim`. For reference, here's the full output of `:scriptnames`. 

```
 1: /etc/vimrc
  2: /usr/share/vim/vim80/syntax/syntax.vim
  3: /usr/share/vim/vim80/syntax/synload.vim
  4: /usr/share/vim/vim80/syntax/syncolor.vim
  5: /usr/share/vim/vim80/filetype.vim
  6: /usr/share/vim/vim80/ftplugin.vim
  7: ~/.vimrc
  8: /usr/share/vim/vim80/ftoff.vim
  9: ~/.vim/bundle/Vundle.vim/autoload/vundle.vim
 10: ~/.vim/bundle/Vundle.vim/autoload/vundle/config.vim
 11: ~/.vim/bundle/vim-json/ftdetect/json.vim
 12: ~/.vim/bundle/vim-javascript/ftdetect/javascript.vim
 13: ~/.vim/bundle/vim-markdown/ftdetect/markdown.vim
 14: /usr/share/vim/vim80/indent.vim
 15: /usr/share/vim/vim80/syntax/nosyntax.vim
 16: ~/.vim/bundle/vim-colorschemes/colors/far.vim
 17: ~/.vim/bundle/vim-fugitive/plugin/fugitive.vim
 18: ~/.vim/bundle/ctrlp.vim/plugin/ctrlp.vim
 19: ~/.vim/bundle/ctrlp.vim/autoload/ctrlp/mrufiles.vim
 20: ~/.vim/bundle/vim-commentary/plugin/commentary.vim
 21: ~/.vim/bundle/vim-indent-guides/plugin/indent_guides.vim
 22: ~/.vim/bundle/vim-indent-guides/autoload/indent_guides.vim
 23: /usr/share/vim/vim80/plugin/getscriptPlugin.vim
 24: /usr/share/vim/vim80/plugin/gzip.vim
 25: /usr/share/vim/vim80/plugin/logiPat.vim
 26: /usr/share/vim/vim80/plugin/manpager.vim
 27: /usr/share/vim/vim80/plugin/matchparen.vim
 28: /usr/share/vim/vim80/plugin/netrwPlugin.vim
 29: /usr/share/vim/vim80/plugin/rrhelper.vim
 30: /usr/share/vim/vim80/plugin/spellfile.vim
 31: /usr/share/vim/vim80/plugin/tarPlugin.vim
 32: /usr/share/vim/vim80/plugin/tohtml.vim
 33: /usr/share/vim/vim80/plugin/vimballPlugin.vim
 34: /usr/share/vim/vim80/plugin/zipPlugin.vim
 35: /usr/share/vim/vim80/ftplugin/javascript.vim
 36: ~/.vim/bundle/vim-javascript/after/ftplugin/javascript.vim
 37: ~/.vim/bundle/vim-javascript/indent/javascript.vim
 38: /usr/share/vim/vim80/indent/javascript.vim
 39: ~/.vim/bundle/vim-javascript/syntax/javascript.vim
 40: /usr/share/vim/vim80/syntax/javascript.vim
 41: ~/.vim/bundle/ctrlp.vim/autoload/ctrlp/utils.vim
```

However, after running `:set ft=css` it seems like vim-css-color did run? However, it didn't highlight any of the colors in the css file. Here's what was added to `:scriptnames` after running `:set ft=css`: 

```
 /usr/share/vim/vim80/ftplugin/css.vim
 43: /usr/share/vim/vim80/indent/css.vim
 44: /usr/share/vim/vim80/syntax/css.vim
 45: ~/.vim/bundle/vim-css-color/after/syntax/css.vim
```

**Comment by ap** [comment]
Well that’s odd.

>     /usr/share/vim/vim80/syntax/nosyntax.vim

Where would that be coming from…? That’s what gets loaded when you do `:syntax off`.

Stupid question: does syntax highlighting work anywhere? The pasted output indicates that it works in Javascript files, but I guess I better ask. And if it does work, does it work *only* in Javascript files? Or does it really only not-work in CSS files?

> However, it didn't highlight any of the colors in the css file.

But it did highlight other parts of the syntax? What does `:syn list cssDefinition` say?

**Comment by ap** [comment]
>     /usr/share/vim/vim80/ftoff.vim

Oy vey. That looks even more suspicious. How much output does `:autocmd filetypedetect` spit out? Dozens and dozens of pages (60 in my case) or just a little bit? Also, is there any mention of `*.css` in there?

(If a command produces lots and lots of output, you can use the following sequence to copy the output into a buffer, so that you can search it etc. Just replace the placeholder with whatever your command is (without the colon), like `autocmd filetypedetect` in this case.)

````vim
:redir => tmpvar
:silent YOUR COMMAND HERE
:redir END
:call setline( 1, split( tmpvar, '\n', 1 ) )
:unlet tmpvar
````

**Comment by tetreault** [comment]
Here's a screenshot with an HTML, CSS, and JS file open in `:vsplit`: https://www.dropbox.com/s/j4kwlmjnrtldw4h/Screenshot%202017-01-18%2019.39.11.png?dl=0

Here's the output of `:syn list cssDefinition`: https://www.dropbox.com/s/fcrs2i92mpjcz5m/Screenshot%202017-01-18%2019.29.44.png?dl=0

As for `:autocmd filetypedetect` I caught this line: out of all the stuff in there: `  *.css     setf css`

**Comment by ap** [comment]
Hmm, all dead ends… I’m afraid I’m out of specific ideas. The most I can think to ask is whether `:set ft?` yields any more sensible value in other buffers.

You could try [my fork of this plugin](https://github.com/ap/vim-css-color) to see if that works when you manually load the syntax – I’m dubious, but it might. But that still won’t solve your core problem of `filetype` not getting set (which is probably due to your configuration)… so I wasn’t going to bring it up until after you had the original plugin working. (Because my fork is much faster and has some extra features.)

I guess you have to take the long way around: disabling everything in your vimrc except Vundle and vim-css-color to see if it works then; and if it does, selectively re-enabling others parts of the vimrc until you find the culprit. Sorry I couldn’t help…

**Comment by tetreault** [comment]
Its all good @ap I appreciate all the help troubleshooting. I'll be sure to remember to ping back here if I get something working so others may see the solution. Thanks again!
