### ISSUE TITLE
After recent update, plugin throws E118 error whenever open a stylesheet

### ISSUE THREAD

**Issue by nightire** [skammer/vim-css-color#22]
Error details:

![2015-03-04 1 09 25](https://cloud.githubusercontent.com/assets/1104018/6478522/c45cb570-c26f-11e4-9b29-bd6c6b6815b3.png)

**Comment by ap** [comment]
Strange. That error is due to a change I made, [in _my_ fork](/ap/vim-css-color) – I recently added another argument to the `init` function in `autoload/css_color.vim`. @skammer’s version of the plugin doesn’t have this file or this function at all, so the bug cannot have anything to do with this fork where you filed the issue.

It also shouldn’t happen, unless you have an extra old non-updated copy of `autoload/css_color.vim` somewhere in your runtime path where it’s taking precedence over the updated one.

Do `:scriptnames` and scan the list, it should contain `/Users/nightire/.vim/bundle/vim-css-color/autoload/css_color.vim` instead of some other copy of `autoload/css_color.vim`. If it contains another copy, there is your problem. If the correct path is being loaded, then I don’t know what the problem could be – all I can think of is to suggest a `git fetch && git reset --hard origin/master`, in case you somehow ended up with an incomplete update… somehow?

**Comment by pallymore** [comment]
hello @ap  
I'm seeing the same issue :/ i don't have any other copy of css_color.vim in my scripts, and my folders are all up to date. 

Btw I'm using MacVim, I looked into MacVim.app and none of its plugin files has `css_color` :/

**Comment by ap** [comment]
Of course they don’t. It’s part of [my plugin](/ap/vim-css-color), which doesn’t ship with Vim.

Does line 261 in your `autoload/css_color.vim` [look like this](/ap/vim-css-color/blob/master/autoload/css_color.vim#L261)?

**Comment by pallymore** [comment]
Yes, I actually copied the file from your repo and replaced the one in my local. still no luck. 
But then I removed the plugin from .vimrc, then reintalled it: 
- `:so ~/.vimrc`
- `:BundleClean`
- Add the plugin back
- `:so ~/.vimrc`
- `:BundleInstall`

then everything seems to be fine now :)

**Comment by ap** [comment]
Odd. But sounds rather like the bug belongs to the plugin manager rather than to me…

Well, at least there’s a workaround. @nightire: does that work for you as well?
